### ISSUE TITLE
Schematic?

### ISSUE THREAD

**Issue by zeljkoavramovic** [Tbruno25/canano#1]
I could not find schematic for canano raspberry pi hat, and I could not find schematic for Arduino Nano shield mentioned in medium.com article.

Is it me missing something obvious, or your intention was to share only code?

**Comment by Tbruno25** [comment]
My arduino shield was not the best as it was one of the first pcb's I ever
made. I'm really happy with the RPI hat, however the schematic is
incomplete as I did a lot of manual routing after the fact. Regardless, I
attached it to this email.

I also have around ~8 RPI Hats left over from my last order. I'd be happy
to send you one for just the cost of shipping!

TJ

**Comment by zeljkoavramovic** [comment]
Thank you for your kind offer, but your RPi hat would not fit my use case. I just wanted to take a look at your schematic, because I will probably decide soon to build a 2xCAN and 2xLIN RPi hat for car hacking purpose. I also wanted to take a look at your Arduino Nano shield schematic because I have one unused physical button on my wheel and I was always annoyed with windshield wiper speed in my car on light rain.

There was no attachment in your mail, so I will use some generic MCP2515 schematic found on the net.

Regards,
Avra
